'use client'
import { Download, RefreshCw, User, AlertTriangle, HelpCircle, CheckCircle } from 'lucide-react'
import type { PRDOutput, PRDInput } from '@/lib/types'

interface Props { output: PRDOutput; input: PRDInput; onReset: () => void }

const PRIORITY_STYLE = {
  'must-have':     { bg: 'rgba(239,68,68,0.1)',   text: '#FCA5A5',  label: 'Must Have' },
  'should-have':   { bg: 'rgba(245,158,11,0.1)',  text: '#FCD34D',  label: 'Should Have' },
  'nice-to-have':  { bg: 'rgba(16,185,129,0.1)',  text: '#6EE7B7',  label: 'Nice to Have' },
}
const EFFORT_STYLE = {
  small:  { bg: 'rgba(16,185,129,0.08)',  text: '#34D399' },
  medium: { bg: 'rgba(245,158,11,0.08)', text: '#FCD34D' },
  large:  { bg: 'rgba(239,68,68,0.08)',  text: '#FCA5A5' },
}
const RISK_COLOR = { high: '#EF4444', medium: '#F59E0B', low: '#10B981' }

function Section({ icon, title, children }: { icon?: React.ReactNode; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-2xl overflow-hidden" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
      <div className="flex items-center gap-2 px-5 py-3 border-b" style={{ borderColor: 'var(--border-default)', background: 'var(--bg-elevated)' }}>
        {icon && <span style={{ color: 'var(--accent-teal)' }}>{icon}</span>}
        <h3 className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{title}</h3>
      </div>
      <div className="p-5">{children}</div>
    </div>
  )
}

function exportMd(o: PRDOutput, i: PRDInput): string {
  const lines = [
    `# Product Requirements Document: ${i.productName}`,
    `**Type:** ${i.productType} · **Stage:** ${i.stage} · **Audience:** ${i.targetAudience}`,
    ``, `## Executive Summary`, o.executiveSummary,
    ``, `## Problem Statement`, o.problemStatement,
    ``, `## Target Market`, o.targetMarket,
    ``, `## Personas`,
    ...o.personas.flatMap(p => [`### ${p.name} — ${p.role}`, `> "${p.quote}"`, `**Goals:** ${p.goals.join(', ')}`, `**Pain Points:** ${p.painPoints.join(', ')}`, ``]),
    `## Use Cases`,
    ...o.useCases.flatMap(u => [`### ${u.title}`, `**Actor:** ${u.actor}`, ...u.steps.map((s,i)=>`${i+1}. ${s}`), `**Outcome:** ${u.outcome}`, ``]),
    `## Feature Roadmap`,
    `| Feature | Description | Priority | Effort | Milestone |`,
    `|---------|-------------|----------|--------|-----------|`,
    ...o.features.map(f => `| ${f.name} | ${f.description} | ${f.priority} | ${f.effort} | ${f.milestone} |`),
    ``, `## Out of Scope`, ...o.outOfScope.map(x => `- ${x}`),
    ``, `## Success Metrics`, ...o.successMetrics.map(m => `- ${m}`),
    ``, `## Risks`,
    `| Risk | Likelihood | Impact | Mitigation |`,
    `|------|-----------|--------|------------|`,
    ...o.risks.map(r => `| ${r.risk} | ${r.likelihood} | ${r.impact} | ${r.mitigation} |`),
    ``, `## Technical Considerations`, o.technicalConsiderations,
    ``, `## Go-to-Market`, o.goToMarket,
    ``, `## Open Questions`, ...o.openQuestions.map(q => `- ❓ ${q}`),
    ``, `---`, `*Generated by PRD Generator AI — validate with your team before committing to build*`,
  ]
  return lines.join('\n')
}

export default function PRDReport({ output, input, onReset }: Props) {
  function handleExport() {
    const blob = new Blob([exportMd(output, input)], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a'); a.href = url
    a.download = `prd-${input.productName.toLowerCase().replace(/\s+/g, '-')}.md`
    a.click(); URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="rounded-2xl p-5 flex items-start justify-between gap-4 flex-wrap" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
        <div>
          <div className="flex items-center gap-2 flex-wrap mb-1.5">
            <span className="text-xs font-bold px-2.5 py-1 rounded-full" style={{ background: 'rgba(13,148,136,0.12)', color: '#5EEAD4' }}>{input.productType}</span>
            <span className="text-xs px-2.5 py-1 rounded-full" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)' }}>{input.stage}</span>
          </div>
          <h1 className="text-2xl font-black mb-1" style={{ color: 'var(--text-primary)' }}>{input.productName}</h1>
          <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>For: {input.targetAudience}</p>
        </div>
        <div className="flex gap-2">
          <button onClick={handleExport} className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)', border: '1px solid var(--border-default)' }}>
            <Download size={14} /> Export .md
          </button>
          <button onClick={onReset} className="flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white" style={{ background: 'var(--accent-grad)' }}>
            <RefreshCw size={14} /> New PRD
          </button>
        </div>
      </div>

      {/* Executive Summary */}
      <Section title="📌 Executive Summary">
        <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.executiveSummary}</p>
      </Section>

      {/* Problem + Market side by side */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Section title="🎯 Problem Statement">
          <p className="text-sm leading-relaxed whitespace-pre-wrap" style={{ color: 'var(--text-secondary)' }}>{output.problemStatement}</p>
        </Section>
        <Section title="📊 Target Market">
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.targetMarket}</p>
        </Section>
      </div>

      {/* Personas */}
      <Section icon={<User size={15} />} title="👤 User Personas">
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {output.personas.map((p, i) => (
            <div key={i} className="rounded-xl p-4" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
              <div className="flex items-center gap-2 mb-2">
                <div className="w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm text-white" style={{ background: 'var(--accent-grad)' }}>{p.name[0]}</div>
                <div><p className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{p.name}</p><p className="text-xs" style={{ color: 'var(--text-dimmer)' }}>{p.role}</p></div>
              </div>
              <p className="text-xs italic mb-3" style={{ color: 'var(--accent-teal)' }}>&ldquo;{p.quote}&rdquo;</p>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <p className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: 'var(--text-dimmer)' }}>Goals</p>
                  {p.goals.map((g, j) => <p key={j} className="text-xs mb-0.5" style={{ color: 'var(--text-secondary)' }}>✓ {g}</p>)}
                </div>
                <div>
                  <p className="text-[9px] font-bold uppercase tracking-wider mb-1" style={{ color: 'var(--text-dimmer)' }}>Pain Points</p>
                  {p.painPoints.map((pt, j) => <p key={j} className="text-xs mb-0.5" style={{ color: '#FCA5A5' }}>✗ {pt}</p>)}
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Use Cases */}
      <Section title="🔄 Use Cases">
        <div className="space-y-3">
          {output.useCases.map((u, i) => (
            <div key={i} className="rounded-xl p-4" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
              <div className="flex items-start gap-3">
                <span className="w-6 h-6 rounded-full text-xs font-bold flex items-center justify-center shrink-0 mt-0.5 text-white" style={{ background: 'var(--accent-grad)' }}>{i + 1}</span>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1.5">
                    <p className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{u.title}</p>
                    <span className="text-xs px-2 py-0.5 rounded-full" style={{ background: 'rgba(13,148,136,0.12)', color: '#5EEAD4' }}>{u.actor}</span>
                  </div>
                  <ol className="list-decimal list-inside space-y-0.5 mb-2">
                    {u.steps.map((s, j) => <li key={j} className="text-xs" style={{ color: 'var(--text-secondary)' }}>{s}</li>)}
                  </ol>
                  <p className="text-xs font-medium" style={{ color: 'var(--accent-green)' }}>→ {u.outcome}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Features */}
      <Section title="🗺 Feature Roadmap">
        <div className="space-y-2">
          {output.features.map((f, i) => {
            const p = PRIORITY_STYLE[f.priority]; const e = EFFORT_STYLE[f.effort]
            return (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
                <div className="flex flex-col gap-1 shrink-0 mt-0.5">
                  <span className="text-[10px] font-bold px-1.5 py-0.5 rounded" style={{ background: p.bg, color: p.text }}>{p.label}</span>
                  <span className="text-[10px] font-bold px-1.5 py-0.5 rounded" style={{ background: e.bg, color: e.text }}>{f.effort}</span>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 flex-wrap">
                    <p className="font-bold text-sm" style={{ color: 'var(--text-primary)' }}>{f.name}</p>
                    <span className="text-[10px] px-2 py-0.5 rounded-full" style={{ background: 'var(--bg-card)', color: 'var(--text-dimmer)', border: '1px solid var(--border-default)' }}>{f.milestone}</span>
                  </div>
                  <p className="text-xs mt-0.5" style={{ color: 'var(--text-secondary)' }}>{f.description}</p>
                </div>
              </div>
            )
          })}
        </div>
      </Section>

      {/* Out of scope + Metrics */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Section title="🚫 Out of Scope">
          <ul className="space-y-1.5">
            {output.outOfScope.map((x, i) => <li key={i} className="text-sm flex gap-2" style={{ color: 'var(--text-secondary)' }}><span style={{ color: '#FCA5A5' }}>✗</span>{x}</li>)}
          </ul>
        </Section>
        <Section icon={<CheckCircle size={14} />} title="✅ Success Metrics">
          <ul className="space-y-1.5">
            {output.successMetrics.map((m, i) => <li key={i} className="text-sm flex gap-2" style={{ color: 'var(--text-secondary)' }}><span style={{ color: '#34D399' }}>✓</span>{m}</li>)}
          </ul>
        </Section>
      </div>

      {/* Risks */}
      <Section icon={<AlertTriangle size={14} />} title="⚠️ Risks & Mitigations">
        <div className="space-y-3">
          {output.risks.map((r, i) => (
            <div key={i} className="p-4 rounded-xl" style={{ background: 'var(--bg-elevated)', border: '1px solid var(--border-default)' }}>
              <div className="flex items-start gap-3">
                <div className="flex flex-col gap-1 shrink-0">
                  <span className="text-[10px] font-bold">Likelihood: <span style={{ color: RISK_COLOR[r.likelihood] }}>{r.likelihood.toUpperCase()}</span></span>
                  <span className="text-[10px] font-bold">Impact: <span style={{ color: RISK_COLOR[r.impact] }}>{r.impact.toUpperCase()}</span></span>
                </div>
                <div>
                  <p className="text-sm font-medium mb-1" style={{ color: 'var(--text-primary)' }}>{r.risk}</p>
                  <p className="text-xs" style={{ color: 'var(--accent-green)' }}>→ {r.mitigation}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </Section>

      {/* Tech + GTM */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <Section title="⚙️ Technical Considerations">
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.technicalConsiderations}</p>
        </Section>
        <Section title="🚀 Go-to-Market">
          <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{output.goToMarket}</p>
        </Section>
      </div>

      {/* Open Questions */}
      <Section icon={<HelpCircle size={14} />} title="❓ Open Questions">
        <div className="space-y-2">
          {output.openQuestions.map((q, i) => (
            <div key={i} className="flex items-start gap-3 p-3 rounded-xl" style={{ background: 'rgba(245,158,11,0.06)', border: '1px solid rgba(245,158,11,0.2)' }}>
              <span className="text-xs font-bold w-5 h-5 rounded-full flex items-center justify-center shrink-0 mt-0.5" style={{ background: 'rgba(245,158,11,0.15)', color: '#FCD34D' }}>{i + 1}</span>
              <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>{q}</p>
            </div>
          ))}
        </div>
      </Section>
    </div>
  )
}
